
[cursor]
#blink = true
style = "beam"
thickness = 0.2
unfocused_hollow = false

[font]
size = 11

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Medium"

[terminal.shell]
program = "/bin/bash"

[window.padding]
x = 30
y = 30

[window]
opacity = 0.99

[general]
import = ["themes/jellybeans.toml"]

[env]
TERM = "xterm-256color"
