general {
    grace = 0
    max_failed_attempts = 5
    failed_attempts_timeout = 300
}

background {
    monitor =
    path = /home/anthony/Imágenes/walls/rural.jpg
    blur_passes = 2
    blur_size = 5
    contrast = 0.9
    brightness = 0.7
}

label {
    monitor =
    text = $TIME
    font_size = 80
    font_family = monospace
    color = rgba(255, 255, 255, 1.0)
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date "+%A, %d de %B"
    font_size = 24
    font_family = monospace
    color = rgba(255, 255, 255, 0.8)
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1] ~/.config/hypr/scripts/music.sh
    font_size = 13
    font_family = monospace
    color = rgba(255, 255, 255, 0.35)
    position = 0, -110
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:30000] ~/.config/hypr/scripts/vpn.sh
    font_size = 12
    font_family = monospace
    color = rgba(255, 255, 255, 0.30)
    position = 0, -140
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.3)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    placeholder_text = Password
    hide_input = false
    fail_text = Contraseña incorrecta
    fail_color = rgba(255, 80, 80, 0.9)
    rounding = -1
    position = 0, -50
    halign = center
    valign = center
}
