#!/bin/bash

# wifi
get_wifi_info() {
    ssid=$(iwgetid -r)
    if [ $? -eq 0 ]; then
        echo "$ssid"
    else
        echo "DISCONNECTED"
    fi
}

# brillo
get_brightness() {
    if command -v brightnessctl >/dev/null 2>&1; then
        brightnessctl -m | awk -F, '{print $4}' | tr -d '%'
    else
        echo "N/A"
    fi
}

while true; do
  BATTERY=$(cat /sys/class/power_supply/BAT0/capacity 2> /dev/null)
  TIME=$(date "+%I:%M %p")
  VOLUME=$(amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d ']' -f 1)
  wifi_info=$(get_wifi_info)
  BRIGHTNESS=$(get_brightness)

  # Mostrar el estado
  xsetroot -name " $TIME | VOL: $VOLUME | BRI: $BRIGHTNESS% | BAT: $BATTERY% | $wifi_info "
done
